AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda that performs a GET request against a provided URL.

Globals:
  Function:
    Runtime: nodejs22.x
    MemorySize: 128
    Timeout: 15
    Tracing: Active
    Architectures:
      - x86_64
    Environment:
      Variables:
        LOG_LEVEL: info

Resources:
  UrlFetchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: url-fetch-function
      Description: Performs GET request for given URL and associates with email (fire-and-forget).
      Handler: handler.handler
      CodeUri: dist
      Policies: []
      # Optionally configure dead-letter queue or destinations later

Outputs:
  FunctionName:
    Value: !Ref UrlFetchFunction
